---
run:
  tests: false

issues:
  exclude-files:
    - ".*_test.go$"

linters:
  enable-all: true
  disable:
    # it should improve to support more known patterns
    - varnamelen
    - nolintlint
    - depguard
    - gomnd
    - execinquery
    # why?
    - tagliatelle
    - ireturn
    - musttag
linters-settings:
  cyclop:
    max-complexity: 15
